# Generated by Django 5.2.4 on 2025-07-31 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_remove_imageoverlay_clip_remove_textoverlay_clip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, null=True)),
                ('video_filename', models.TextField(blank=True, null=True)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('crop', models.CharField(choices=[('9:16', 'Vertical (9:16)'), ('1:1', 'Square (1:1)')], default='9:16', max_length=10)),
                ('subtitles_flag', models.BooleanField(default=False)),
                ('subtitles_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('subtitles_size', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('error', 'Ошибка')], db_index=True, default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
