# Generated by Django 5.2.4 on 2025-07-31 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='subtitles_color',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='subtitles_flag',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='subtitles_size',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='text',
        ),
    ]
