# Generated by Django 5.2.4 on 2025-07-24 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_path', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('error', 'Ошибка')], db_index=True, default='queued', max_length=20)),
                ('timecodes_path', models.TextField(blank=True, null=True)),
                ('interesting_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
