# Generated by Django 5.2.4 on 2025-07-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_video_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='interesting_path',
            new_name='interesting_filename',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='timecodes_path',
            new_name='timecodes_filename',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='video_path',
            new_name='video_filename',
        ),
    ]
