# Generated by Django 5.2.4 on 2025-07-29 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_interesting_path_project_interesting_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('video_format', models.CharField(choices=[('9:16', 'Vertical (9:16)'), ('1:1', 'Square (1:1)')], default='9:16', max_length=10)),
                ('subtitles_enabled', models.BooleanField(default=False)),
                ('subtitles_color', models.CharField(default='white', max_length=20)),
                ('face_tracking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
