# Generated by Django 5.2.4 on 2025-07-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='text',
            field=models.CharField(blank=True, null=True),
        ),
    ]
