# Generated by Django 5.2.4 on 2025-07-30 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_clip_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='interesting_filename',
            new_name='subtitles_filename',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='subtitles_color',
        ),
    ]
