# Generated by Django 5.2.4 on 2025-07-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_interesting_filename_project_subtitles_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='video_format',
            new_name='crop',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='timecodes_filename',
            new_name='interesting_filename',
        ),
    ]
