# Generated by Django 5.2.4 on 2025-07-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_video_format_clip_crop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clip',
            old_name='face_tracking',
            new_name='face_tracking_flag',
        ),
        migrations.RenameField(
            model_name='clip',
            old_name='subtitles_enabled',
            new_name='subtitles_flag',
        ),
        migrations.AddField(
            model_name='clip',
            name='subtitles_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='subtitles_size',
            field=models.IntegerField(null=True),
        ),
    ]
