# Generated by Django 5.2.4 on 2025-07-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_face_tracking_clip_face_tracking_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('error', 'Ошибка')], db_index=True, default='queued', max_length=20),
        ),
    ]
