# Generated by Django 5.2.4 on 2025-07-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_clip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='video_filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
