# Generated by Django 5.2.4 on 2025-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_clip_video_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
