# Generated by Django 5.2.4 on 2025-07-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_clip_subtitles_color_alter_clip_subtitles_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='face_tracking_flag',
        ),
    ]
