# Generated by Django 5.2.4 on 2025-07-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_textoverlaycomponent_clip_imageoverlay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageoverlay',
            name='image_file',
        ),
        migrations.AddField(
            model_name='imageoverlay',
            name='image_filename',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
