# Generated by Django 5.2.4 on 2025-07-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_imageoverlay_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageoverlay',
            name='end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageoverlay',
            name='start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='end',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textoverlay',
            name='start',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
