# Generated by Django 5.2.4 on 2025-07-30 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_imageoverlay_end_imageoverlay_start_textoverlay_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='textoverlay',
            name='user',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='text_overlays', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
