# Generated by Django 5.2.4 on 2025-07-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_textoverlay_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageoverlay',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='textoverlay',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='imageoverlay',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textoverlay',
            name='user',
        ),
        migrations.DeleteModel(
            name='Clip',
        ),
        migrations.DeleteModel(
            name='ImageOverlay',
        ),
        migrations.DeleteModel(
            name='TextOverlay',
        ),
    ]
