# Generated by Django 5.2.4 on 2025-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_imageoverlay_clip_remove_textoverlay_clip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tracking_filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
