# Generated by Django 5.2.4 on 2025-07-31 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOverlay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_filename', models.TextField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_overlays', to='clips.clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_overlays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextOverlay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('font_size', models.PositiveIntegerField(default=60)),
                ('font_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_overlays', to='clips.clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_overlays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
